### ISSUE TITLE
How about WGAN-GP?

### ISSUE THREAD

**Issue by plutoyuxie** [yiranran/APDrawingGAN#3]
Hello, 

Appreciate your work!
Since Wasserstein GAN with Gradient Penalty is often used recently, 
I wonder if you tried that? 

Thanks

**Comment by yiranran** [comment]
I haven't tried WGAN-GP. But since my code is largely borrowed from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.
I think their repository has implemented WGAN-GP now, you can simply replace current GANLoss with GANLoss in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py to try wgangp.

**Comment by plutoyuxie** [comment]
> I haven't tried WGAN-GP. But since my code is largely borrowed from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.
> I think their repository has implemented WGAN-GP now, you can simply replace current GANLoss with GANLoss in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py to try wgangp.

I see. Thank you and thank the artist. Those drawings in the dataset are fineness.
