### ISSUE TITLE
Align face images with smaller size

### ISSUE THREAD

**Issue by ichuniq** [yiranran/APDrawingGAN#4]
Hi,
In the provided matlab code [face_align_512.m](https://github.com/yiranran/APDrawingGAN/blob/master/preprocess/face_align_512.m#L15) , I'm curious about the reason behind this line of code
 `coord5point = (coord5point-240)/560 * 512 + 256;` 

since I'm trying to preprocess smaller image (e.g. 128x128)  as input which cost less time and memory usage.

Looking forward to some help, thanks!

**Comment by yiranran** [comment]
I think you can modify the matlab code by replacing the line with "coord5point = (coord5point-240)/560 * 128 + 64;" (for 128x128 image). Then all facial landmark files need to be updated.
And you may need to retrain the network, since the pretrained network was trained on 512x512 image.
And you may need to change some options on image size, e.g. --loadSize, --fineSize, --EYE_H, --EYE_W, --NOSE_H, --NOSE_W, --MOUTH_H, --MOUTH_W, all divided by 4. And the network structure needs to be adjusted accordingly, e.g. --netG unet_256 replaced by unet_128.
